management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    config-props:
      show-values: always
    env:
      show-values: always
    loggers:
      enabled: true